### ISSUE TITLE
import StockDataFrame出错

### ISSUE THREAD

**Issue by Dclpwos** [jealous/stockstats#177]
Traceback (most recent call last):
  File "G:\quantProjects\DRLquant\Ashare_example\tset.py", line 1, in <module>
    from stockstats import StockDataFrame as Sdf
  File "D:\ProgramData\Miniconda3\envs\DRLstock\Lib\site-packages\stockstats.py", line 94, in <module>
    def set_dft_window(name: str, windows: Union[int, tuple[int, ...]]):
TypeError: 'type' object is not subscriptable

**Comment by Dclpwos** [comment]
解决了，# At the top of the code, along with the other `import`s
from __future__ import annotations

**Comment by CYLEE21** [comment]
Could you make it more specific? I also have the same error message.

**Comment by jealous** [comment]
At the beginning of the code, try adding `from future import annotations`
