### ISSUE TITLE
import Error "TypeError: 'type' object is not subscriptable"

### ISSUE THREAD

**Issue by CYLEE21** [jealous/stockstats#179]
```
from stockstats import wrap
```
does not work, it shows the following error messages.

```
     43     pass
     46 _dft_windows = {
     47     # sort alphabetically
     48     'ao': (5, 34),
   (...)
     90     'vwma': 14,
     91 }
---> 94 def set_dft_window(name: str, windows: Union[int, tuple[int, ...]]):
     95     ret = _dft_windows.get(name)
     96     _dft_windows[name] = windows

TypeError: 'type' object is not subscriptable
```

**Comment by jealous** [comment]
Please try adding `from future import annotations` at the beginning of the code.

**Comment by CYLEE21** [comment]
It shows the following error
```
ImportError: cannot import name 'annotations' from 'future'
```
is future this pacakge? https://pypi.org/project/future/

**Comment by jealous** [comment]
I think it's a built in package.  
https://docs.python.org/3/library/__future__.html

Could you try `from __future__ import annotations`?

**Comment by chenqs71** [comment]
add string ',annotations' at the end of line 27 in stockstats.py

**Comment by wrx1990** [comment]
> add string ',annotations' at the end of line 27 in stockstats.py在 stockstats.py 中第 27 行末尾添加字符串 ',annotations'

it,worked.
![image](https://github.com/jealous/stockstats/assets/104119730/b5e1d023-2847-4f49-90ac-cc8aa2c66155)
![image](https://github.com/jealous/stockstats/assets/104119730/2d7f298f-43f8-45eb-8cb8-6d0aa78ee95b)

**Comment by code4passion** [comment]
This doesnt work for me

from __future__ import unicode_literals, annotations
from stockstats import wrap


Traceback (most recent call last):
  File "/Users/dshetyo/PycharmProjects/timeseries-predictor/model_trainer.py", line 10, in <module>
    from data_util import get_data
  File "/Users/dshetyo/PycharmProjects/timeseries-predictor/data_util.py", line 2, in <module>
    from stockstats import wrap
  File "/Users/dshetyo/anaconda3/envs/timeseries/lib/python3.8/site-packages/stockstats.py", line 94, in <module>
    def set_dft_window(name: str, windows: Union[int, tuple[int, ...]]):
TypeError: 'type' object is not subscriptable

**Comment by CYLEE21** [comment]
My original problem has been solved by changing the python version. 
This library has specified the recommened python version.
I hope this helps.

**Comment by jealous** [comment]
What's the python version that has this error?
