### ISSUE TITLE
Unable to extract SMA data

### ISSUE THREAD

**Issue by arunsivaraj** [jealous/stockstats#36]
I was trying to extract SMA values from the dataframe, but the code is throwing error. Pasted below is my code and error details.  
```
results = Sdf.retype(get_history(symbol =AAPL,start=date(2018,03,27),end=date(2018,06,05),index=False))
data_sma=results['open_2_sma']
print (data_sma[-1])
```

Error message:
No handlers could be found for logger "stockstats"

Traceback (most recent call last):
  File "C:\Python27\Practises\Investing\StockStats\Training.py", line 35, in <module>
    print ("SMA:",results['data_sma'][-1])
  File "C:\Python27\lib\site-packages\stockstats.py", line 929, in __getitem__
    super(StockDataFrame, self).__getitem__(item))
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "C:\Python27\lib\site-packages\pandas\core\internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "C:\Python27\lib\site-packages\pandas\core\indexes\base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'data_sma'

**Comment by jealous** [comment]
Not reproducible.  I can retrieve the data.
```python        
        import pandas_datareader.data as web
        start = '2018-03-27'
        end = '2018-06-05'
        df = web.DataReader(name='AAPL', data_source='stooq', start=start,
                            end=end)
        print(df)
        data = wrap(df)
        print(data['open_2_sma'])
```
