### ISSUE TITLE
Can't get DMI

### ISSUE THREAD

**Issue by josebalius** [jealous/stockstats#42]
```
Traceback (most recent call last):
  File "bollinger.py", line 150, in <module>
    main()
  File "bollinger.py", line 146, in main
    print(execute(symbol))
  File "bollinger.py", line 74, in execute
    sdf['pdi'] = sdf._get_pdi(sdf, 14)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 545, in _get_pdi
    df[pdi_column] = df[pdm_column] / df[tr_column] * 100
  File "/Library/Python/2.7/site-packages/stockstats.py", line 925, in __getitem__
    self.init_columns(self, item)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 858, in init_columns
    StockDataFrame.__init_column(obj, columns)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 917, in __init_column
    StockDataFrame.__init_not_exist_column(df, key)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 909, in __init_not_exist_column
    getattr(cls, func_name)(df, r)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 480, in _get_pdm
    um, dm = df['um'], df['dm']
  File "/Library/Python/2.7/site-packages/stockstats.py", line 925, in __getitem__
    self.init_columns(self, item)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 858, in init_columns
    StockDataFrame.__init_column(obj, columns)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 917, in __init_column
    StockDataFrame.__init_not_exist_column(df, key)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 883, in __init_not_exist_column
    cls._get_um_dm(df)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 464, in _get_um_dm
    hd = df['high_delta']
  File "/Library/Python/2.7/site-packages/stockstats.py", line 925, in __getitem__
    self.init_columns(self, item)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 858, in init_columns
    StockDataFrame.__init_column(obj, columns)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 917, in __init_column
    StockDataFrame.__init_not_exist_column(df, key)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 895, in __init_not_exist_column
    cls._get_delta(df, key)
  File "/Library/Python/2.7/site-packages/stockstats.py", line 831, in _get_delta
    df[key] = df[key_to_delta].diff()
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 1412, in diff
    result = algorithms.diff(_values_from_object(self), periods)
  File "/Library/Python/2.7/site-packages/pandas/core/algorithms.py", line 1635, in diff
    out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]
TypeError: unsupported operand type(s) for -: 'unicode' and 'unicode'
```
```
sdf['pdi'] = sdf.get('pdi')
```

**Comment by jealous** [comment]
Hi @josebalius , could you share your data?

**Comment by josebalius** [comment]
@jealous False report sorry, my data had the quotes in strings and not parsed to floats, once I parsed everything to floats first, it all started working. Thank you for this library!
