### ISSUE TITLE
rsi doesn't seem to work with pandas 1.2.0

### ISSUE THREAD

**Issue by itrascastro** [jealous/stockstats#68]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rsi_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/stockstats.py", line 1021, in __getitem__
    super(StockDataFrame, self).__getitem__(item))
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'rsi_12'

**Comment by itrascastro** [comment]
In my case it was due to the type of the columns. I solve it converting to float

**Comment by glebarez** [comment]
type-checking must be done inside stockstats omg
this error is misleading and frustrating
plz fix this
